POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbmVkb2UiLCJpZCI6IjYzODM3NWU4YWVlZjAxYzQzMTBhYThlNyIsImlhdCI6MTY2OTU2MjQ1Nn0.HY8X4yhhwg05DnnL178dUaLdZxRMydW9zteQbPlbglA

{
  "title": "The origin of the women",
  "author": "Jane Doe",
  "url": "http://janeoeblog.com/the-origin-women",
  "likes": 0,
  "user": "638375e8aeef01c4310aa8e7"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbmVkb2UiLCJpZCI6IjYzODM3NWU4YWVlZjAxYzQzMTBhYThlNyIsImlhdCI6MTY2OTU2MjQ1Nn0.HY8X4yhhwg05DnnL178dUaLdZxRMydW9zteQbPlbglA

{
  "title": "The origin of the wine",
  "author": "Jane Doe",
  "url": "http://janeoeblog.com/the-origin-wine",
  "likes": 0,
  "user": "638375e8aeef01c4310aa8e7"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbmVkb2UiLCJpZCI6IjYzODM3NWU4YWVlZjAxYzQzMTBhYThlNyIsImlhdCI6MTY3MDQyNjE2NiwiZXhwIjoxNjcwNDI5NzY2fQ.KuHJti6mflZYwLWigWYrRr1ZwK99SZ9YLqukxuNWuW0

{
  "title": "The origin of the mankind",
  "author": "John Doe",
  "url": "http://johnoeblog.com/the-origin-mankind",
  "likes": 0,
  "user": "638375e2aeef01c4310aa8e4"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UiLCJpZCI6IjYzODM3NWUyYWVlZjAxYzQzMTBhYThlNCIsImlhdCI6MTY2OTU2MjQzM30.XbAPjUC7VRFMWlvLTsX6S_UY_PtXoBghCXDrbPdS9Zg

{
  "title": "The origin of the trees",
  "author": "John Doe",
  "url": "http://janeoeblog.com/the-origin-trees",
  "likes": 0,
  "user": "638375e2aeef01c4310aa8e4"
}

###

POST http://localhost:3003/api/blogs/63839da69970c0fc97b71513/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbmVkb2UiLCJpZCI6IjYzODM3NWU4YWVlZjAxYzQzMTBhYThlNyIsImlhdCI6MTY3MDQyNjE2NiwiZXhwIjoxNjcwNDI5NzY2fQ.KuHJti6mflZYwLWigWYrRr1ZwK99SZ9YLqukxuNWuW0

{
  "comment": "Great job as usual Jane. Keep it up."
}