POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "username": "johndoe",
  "password": "password"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "username": "janedoe",
  "password": "password"
}